# Generated by Django 6.0.1 on 2026-02-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='脚本名称')),
                ('content', models.TextField(verbose_name='脚本内容')),
                ('description', models.TextField(blank=True, null=True, verbose_name='脚本描述')),
            ],
            options={
                'db_table': 'script',
            },
        ),
    ]
